#!/bin/sh
#
# Start IMU Daemon
#

start() {
	printf "Starting IMU Daemon: "
	source /etc/profile
	imu-daemon -d -r50 -g250 -a2
	imu-socket -d -tu -p1111
	echo "OK"
}

stop() {
	printf "Stopping IMU Daemon: "
	killall imu-socket
	killall imu-daemon
	echo "OK"
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	stop
	start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
