#!/bin/sh
#
# Start DBus Launch
#

start() {
	printf "Starting DBus Session: "
	mkdir -p /etc/profile.d/
	dbus-launch --sh-syntax > /etc/profile.d/dbus-env.sh
	echo "OK"
}

stop() {
	printf "Stopping DBus Session: "
	DBUS_SESSION_BUS_PID=$(cat /etc/profile.d/dbus-env.sh | grep PID | grep -oE "[0-9]*")
	kill -9 $DBUS_SESSION_BUS_PID
	echo "OK"
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	stop
	start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
